#!/bin/bash

# Grub customization for default linux entries
function grub_customization {
  dpkg-divert --package netrunner-settings-grub --add --rename --divert /usr/share/netrunner/grub_10_linux.orig /etc/grub.d/10_linux
}

if [ install = "$1" -o upgrade = "$1" ]; then
  grub_customization
fi 
